<?php
/* This file was generated by the install process. You can edit it. Please see config.php to understand the configuration items. */
$cfg['web_root'] = 'https://${NOMDHOTE}/';
$cfg['var_root'] = '${DOCROOT}/';
$cfg['lang'] = 'fr_FR.UTF-8';
$cfg['style'] = 'default';
$cfg['rewrite'] = false;
$cfg['password'] = '';
?>
