Document: hostathome
Title: Debian hostathome Manual
Author: <insert document author here>
Abstract: This manual describes what hostathome is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hostathome/hostathome.sgml.gz

Format: postscript
Files: /usr/share/doc/hostathome/hostathome.ps.gz

Format: text
Files: /usr/share/doc/hostathome/hostathome.text.gz

Format: HTML
Index: /usr/share/doc/hostathome/html/index.html
Files: /usr/share/doc/hostathome/html/*.html
